### PR TITLE
Stop Commenting

### PR DESCRIPTION
**Pull request by JCBurnside**
TADA

### CODE REVIEW

**Comment by Jackattack1717** [comment]
gr8 b8 m8 i r8 8/8. best game 2k16.

**Comment by ClockwerkVince** [comment]
I am dissapointed

**Comment by vtlanglois** [comment]
I'm really dumb

**Comment by vtlanglois** [comment]
And his name is jon cena

**Comment by RcRacer** [comment]
What?!

**Comment by MatthewGaby** [comment]
Dah Dah Dah DUUUUUUUUUUUUUUU

**Comment by Jackattack1717** [comment]
<a href="http://instantcena.com/">lol click this link</a>

**Comment by JCBurnside** [comment]
?

**Comment by MatthewGaby** [comment]
i can't see

**Comment by RcRacer** [comment]
You have eyes

**Comment by MatthewGaby** [comment]
<a href="https://www.youtube.com/watch?v=wGCoAFZiYMw">no i have a computer screen</a>

**Comment by RcRacer** [comment]
-_- Not what I was talking about

**Comment by MatthewGaby** [comment]
poke

**Comment by JCBurnside** [comment]
_insert really bad star wars joke here_

**Pull request merged**
